---
- name: install apache2
  apt: name={{ item }} state=latest
  with_items:
    - apache2
    - php5-curl
    - libapache2-mod-php5

- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present

- name: apache2 listen on port {{ http_port }}
  lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ http_port }}" state=present

# - name: apache2 virtualhost on port {{ http_port }}
  # lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:" line="<VirtualHost *:{{ http_port }}>"

- name: create virtual host file
  template: src=virtualhost.conf.j2 dest=/etc/apache2/sites-available/{{ domain }}.conf

- name: a2ensite {{ domain }}
  command: a2ensite {{ domain }}
  args:
    creates: /etc/apache2/sites-enabled/{{ domain }}.conf
  notify:
    - restart apache2